# Markdownlint configuration for Terraform Provider documentation
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
#
# Strict configuration - generators must produce compliant markdown

# Disable line length - Terraform descriptions are legitimately long
MD013: false

# Allow inline HTML - terraform-docs uses anchor tags for navigation (standard practice)
MD033: false

# All other rules enabled by default
