---
extends: default
ignore: |
  vendor/
  node_modules/
  docs/specifications/
rules:
  line-length: disable
  truthy:
    allowed-values: ["true", "false", "on"]
  comments:
    min-spaces-from-content: 1
