// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
)

var (
	_ resource.Resource                = &DNSZoneResource{}
	_ resource.ResourceWithConfigure   = &DNSZoneResource{}
	_ resource.ResourceWithImportState = &DNSZoneResource{}
)

func NewDNSZoneResource() resource.Resource {
	return &DNSZoneResource{}
}

type DNSZoneResource struct {
	client *client.Client
}

type DNSZoneResourceModel struct {
	Name types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Labels types.Map `tfsdk:"labels"`
	Annotations types.Map `tfsdk:"annotations"`
	ID types.String `tfsdk:"id"`
	AllowHTTPLbManagedRecords types.Bool `tfsdk:"allow_http_lb_managed_records"`
}

func (r *DNSZoneResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dns_zone"
}

func (r *DNSZoneResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a DNSZone in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the DNSZone. Must be unique within the namespace.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the DNSZone will be created.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"allow_http_lb_managed_records": schema.BoolAttribute{
				MarkdownDescription: "Option to allow user-created HTTP, TCP, and CDN load balancer related resource records to be automatically managed in a protected RRset.",
				Optional: true,
			},
		},
		Blocks: map[string]schema.Block{
			"default_rr_set_group": schema.ListNestedBlock{
				MarkdownDescription: "Add and manage DNS resource record sets part of Default set group. ves.io.schema.rules.repeated.max_items: 50000",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"description": schema.StringAttribute{
							MarkdownDescription: "Comment.",
							Optional: true,
						},
						"ttl": schema.Int64Attribute{
							MarkdownDescription: "Time to live. ves.io.schema.rules.uint32.gte: 60 ves.io.schema.rules.uint32.lte: 2147483647",
							Optional: true,
						},
					},
					Blocks: map[string]schema.Block{
						"a_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSAResourceRecord. A Records",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). A Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"values": schema.ListAttribute{
									MarkdownDescription: "IPv4 Addresses. A valid IPv4 address, for example: 1.1.1.1 Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.ipv4: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
									Optional: true,
									ElementType: types.StringType,
								},
							},
						},
						"aaaa_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSAAAAResourceRecord. RecordSet for AAAA Records",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). AAAA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"values": schema.ListAttribute{
									MarkdownDescription: "IPv6 Addresses. A valid IPv6 address, for example: 2001:0db8:85a3:0000:0000:8a2e:0370:7334 Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.ipv6: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
									Optional: true,
									ElementType: types.StringType,
								},
							},
						},
						"afsdb_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS AFSDB Record. DNS AFSDB Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). AFSDB Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "AFSDB Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"hostname": schema.StringAttribute{
												MarkdownDescription: "Hostname. Server name of the AFS cell database server or the DCE name server. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.hostname: true",
												Optional: true,
											},
											"subtype": schema.StringAttribute{
												MarkdownDescription: "AFSDB Record Subtype. AFS Volume Location Server or DCE Authentication Server. - NONE: NONE - AFSVolumeLocationServer: AFS Volume Location Server - DCEAuthenticationServer: DCE Authentication Server",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"alias_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSAliasResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"value": schema.StringAttribute{
									MarkdownDescription: "Domain. A valid domain name, for example: example.com ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 255",
									Optional: true,
								},
							},
						},
						"caa_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSCAAResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). CAA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "CAA Record Value. ves.io.schema.rules.repeated.max_items: 100",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"flags": schema.Int64Attribute{
												MarkdownDescription: "Flags. This flag should be an integer between 0 and 255. ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 255",
												Optional: true,
											},
											"tag": schema.StringAttribute{
												MarkdownDescription: "Tag.",
												Optional: true,
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "Value. ves.io.schema.rules.string.max_len: 1024 ves.io.schema.rules.string.min_len: 1",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"cds_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS CDS Record. DNS CDS Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). CDS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "DS Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"ds_key_algorithm": schema.StringAttribute{
												MarkdownDescription: "DS Key algorithm. DS key value must be compatible with the specified algorithm. - UNSPECIFIED: UNSPECIFIED - RSASHA1: RSASHA1 - RSASHA1NSEC3SHA1: RSASHA1-NSEC3-SHA1 - RSASHA256: RSASHA256 - RSASHA512: RSASHA512 - ECDSAP256SHA256: ECDSAP256SHA256 - ECDSAP384SHA384: ECDSAP384SHA384 - ED25519: ED25519 - ED448: ED448",
												Optional: true,
											},
											"key_tag": schema.Int64Attribute{
												MarkdownDescription: "Key Tag. A short numeric value which can help quickly identify the referenced DNSKEY-record. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"sha1_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA1 Digest.",
											},
											"sha256_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA256 Digest.",
											},
											"sha384_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA384 Digest.",
											},
										},
									},
								},
							},
						},
						"cert_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS CERT Record. DNS CERT Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). CERT Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "CERT Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"algorithm": schema.StringAttribute{
												MarkdownDescription: "CERT Algorithm. CERT algorithm value must be compatible with the specified algorithm. - RESERVEDALGORITHM: RESERVEDALGORITHM - RSAMD5: RSAMD5 - DH: DH - DSASHA1: DSASHA1 - ECC: ECC - RSASHA1ALGORITHM: RSA-SHA1 - INDIRECT: INDIRECT - PRIVATEDNS: PRIVATEDNS - PRIVATEOID: PRIVATEOID",
												Optional: true,
											},
											"cert_key_tag": schema.Int64Attribute{
												MarkdownDescription: "Key Tag. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
											"cert_type": schema.StringAttribute{
												MarkdownDescription: "CERT Type. CERT type value must be compatible with the specified types. - INVALIDCERTTYPE: INVALIDCERTTYPE - PKIX: PKIX - SPKI: SPKI - PGP: PGP - IPKIX: IPKIX - ISPKI: ISPKI - IPGP: IPGP - ACPKIX: ACPKIX - IACPKIX: IACPKIX - URI_: URI - OID: OID",
												Optional: true,
											},
											"certificate": schema.StringAttribute{
												MarkdownDescription: "Certificate. Certificate in base 64 format. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 4096 ves.io.schema.rules.string.min_len: 1",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"cname_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSCNAMEResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). CName Record name, please provide only the specific subdomain or record name without the base domain. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.pattern: ^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"value": schema.StringAttribute{
									MarkdownDescription: "Domain. ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 255",
									Optional: true,
								},
							},
						},
						"ds_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS DS Record. DNS DS Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). DS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "DS Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"ds_key_algorithm": schema.StringAttribute{
												MarkdownDescription: "DS Key algorithm. DS key value must be compatible with the specified algorithm. - UNSPECIFIED: UNSPECIFIED - RSASHA1: RSASHA1 - RSASHA1NSEC3SHA1: RSASHA1-NSEC3-SHA1 - RSASHA256: RSASHA256 - RSASHA512: RSASHA512 - ECDSAP256SHA256: ECDSAP256SHA256 - ECDSAP384SHA384: ECDSAP384SHA384 - ED25519: ED25519 - ED448: ED448",
												Optional: true,
											},
											"key_tag": schema.Int64Attribute{
												MarkdownDescription: "Key Tag. A short numeric value which can help quickly identify the referenced DNSKEY-record. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"sha1_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA1 Digest.",
											},
											"sha256_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA256 Digest.",
											},
											"sha384_digest": schema.SingleNestedBlock{
												MarkdownDescription: "SHA384 Digest.",
											},
										},
									},
								},
							},
						},
						"eui48_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS EUI48 Record. DNS EUI48 Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). EUI48 Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
								"value": schema.StringAttribute{
									MarkdownDescription: "EUI48 Identifier. A valid eui48 identifier, for example: 01-23-45-67-89-ab Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 17 ves.io.schema.rules.string.min_len: 17 ves.io.schema.rules.string.pattern: ^([0-9A-Fa-f]{2}-){5}([0-9A-Fa-f]{2})$",
									Optional: true,
								},
							},
						},
						"eui64_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS EUI64 Record. DNS EUI64 Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). EUI64 Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
								"value": schema.StringAttribute{
									MarkdownDescription: "EUI64 Identifier. A valid EUI64 identifier, for example: 01-23-45-67-89-ab-cd-ef Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 23 ves.io.schema.rules.string.min_len: 23 ves.io.schema.rules.string.pattern: ^([0-9A-Fa-f]{2}-){7}([0-9A-Fa-f]{2})$",
									Optional: true,
								},
							},
						},
						"lb_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS Load Balancer Record. DNS Load Balancer Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). Load Balancer record name (except for SRV DNS Load balancer record) should be a simple record name and not a subdomain of a subdomain. ves.io.schema.rules.string.max_len: 255",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"value": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
							},
						},
						"loc_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS LOC Record. DNS LOC Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). LOC Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "LOC Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"altitude": schema.Int64Attribute{
												MarkdownDescription: "Altitude. Altitude in meters Required: YES ves.io.schema.rules.float.gte: -100000.00 ves.io.schema.rules.float.lte: 42849672.95 ves.io.schema.rules.message.required: true",
												Optional: true,
											},
											"horizontal_precision": schema.Int64Attribute{
												MarkdownDescription: "Horizontal Precision. Horizontal Precision in meters ves.io.schema.rules.float.gte: 0.0 ves.io.schema.rules.float.lte: 90000000.00",
												Optional: true,
											},
											"latitude_degree": schema.Int64Attribute{
												MarkdownDescription: "Latitude degree. Latitude degree, an integer between 0 and 90, including 0 and 90 Required: YES ves.io.schema.rules.int32.gte: 0 ves.io.schema.rules.int32.lte: 90 ves.io.schema.rules.message.required: true",
												Optional: true,
											},
											"latitude_hemisphere": schema.StringAttribute{
												MarkdownDescription: "Latitude hemisphere. Latitude hemisphere can only be N or S - N: North Hemisphere - S: South Hemisphere",
												Optional: true,
											},
											"latitude_minute": schema.Int64Attribute{
												MarkdownDescription: "Latitude minute. Latitude minute, an integer between 0 and 59, including 0 and 59 ves.io.schema.rules.int32.gte: 0 ves.io.schema.rules.int32.lte: 59",
												Optional: true,
											},
											"latitude_second": schema.Int64Attribute{
												MarkdownDescription: "Latitude second. Latitude second, an decimal between 0 and 59.999, including 0 and 59.999 ves.io.schema.rules.float.gte: 0.0 ves.io.schema.rules.float.lte: 59.999",
												Optional: true,
											},
											"location_diameter": schema.Int64Attribute{
												MarkdownDescription: "Size. Diameter of a sphere enclosing the described entity, in meters ves.io.schema.rules.float.gte: 0.0 ves.io.schema.rules.float.lte: 90000000.00",
												Optional: true,
											},
											"longitude_degree": schema.Int64Attribute{
												MarkdownDescription: "Longitude degree. Longitude degree, an integer between 0 and 180, including 0 and 180 Required: YES ves.io.schema.rules.int32.gte: 0 ves.io.schema.rules.int32.lte: 180 ves.io.schema.rules.message.required: true",
												Optional: true,
											},
											"longitude_hemisphere": schema.StringAttribute{
												MarkdownDescription: "Longitude hemisphere. Longitude hemisphere can only be E or W - E: East Hemisphere - W: West Hemisphere",
												Optional: true,
											},
											"longitude_minute": schema.Int64Attribute{
												MarkdownDescription: "Longitude minute. Longitude minute, an integer between 0 and 59, including 0 and 59 ves.io.schema.rules.int32.gte: 0 ves.io.schema.rules.int32.lte: 59",
												Optional: true,
											},
											"longitude_second": schema.Int64Attribute{
												MarkdownDescription: "Longitude second. Longitude second, an decimal between 0 and 59.999, including 0 and 59.999 ves.io.schema.rules.float.gte: 0.0 ves.io.schema.rules.float.lte: 59.999",
												Optional: true,
											},
											"vertical_precision": schema.Int64Attribute{
												MarkdownDescription: "Vertical Precision. Vertical Precision in meters ves.io.schema.rules.float.gte: 0.0 ves.io.schema.rules.float.lte: 90000000.00",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"mx_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSMXResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). MX Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "MX Record Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"domain": schema.StringAttribute{
												MarkdownDescription: "Domain. Mail exchanger domain name, please provide the full hostname, for example: mail.example.com ves.io.schema.rules.string.hostname: true",
												Optional: true,
											},
											"priority": schema.Int64Attribute{
												MarkdownDescription: "Priority. Mail exchanger priority code ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"naptr_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS NAPTR Record. DNS NAPTR Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). NAPTR Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "NAPTR Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"flags": schema.StringAttribute{
												MarkdownDescription: "Flags. Flag to control aspects of the rewriting and interpretation of the fields in the record. At this time only four flags, S/A/U/P, are defined. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 255 ves.io.schema.rules.string.pattern: ^(S|s|A|a|U|u|P|p)$",
												Optional: true,
											},
											"order": schema.Int64Attribute{
												MarkdownDescription: "Order. Order in which the NAPTR records must be processed. A lower number indicates a higher preference. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
											"preference": schema.Int64Attribute{
												MarkdownDescription: "Preference. Preference when records have the same order. A lower number indicates a higher preference. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
											"regexp": schema.StringAttribute{
												MarkdownDescription: "Regular Expression. Regular expression to construct the next domain name to lookup. ves.io.schema.rules.string.max_len: 255",
												Optional: true,
											},
											"replacement": schema.StringAttribute{
												MarkdownDescription: "Replacement. The next NAME to query for NAPTR, SRV, or address records depending on the value of the flags field.",
												Optional: true,
											},
											"service": schema.StringAttribute{
												MarkdownDescription: "Protocol Resolution Service. Specifies the service(s) available down this rewrite path. ves.io.schema.rules.string.max_len: 255 ves.io.schema.rules.string.pattern: ^([A-Za-z][A-Za-z0-9]{0,31}(\\+[A-Za-z][A-Za-z0-9]{0,31})*$|^$)",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"ns_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSNSResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). NS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"values": schema.ListAttribute{
									MarkdownDescription: "Name Servers. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.hostname: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
									Optional: true,
									ElementType: types.StringType,
								},
							},
						},
						"ptr_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSPTRResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). PTR Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"values": schema.ListAttribute{
									MarkdownDescription: "Domain Name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.hostname: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
									Optional: true,
									ElementType: types.StringType,
								},
							},
						},
						"srv_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSSRVResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). SRV Record name, please provide only the specific subdomain or record name without the base domain. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.pattern: ^([*]|[a-zA-Z0-9-_]{1,63})([.][a-zA-Z0-9-_]{1,63})*$",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "SRV Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"port": schema.Int64Attribute{
												MarkdownDescription: "Port. Port on which the service can be found ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
											"priority": schema.Int64Attribute{
												MarkdownDescription: "Priority. Priority of the target. A lower number indicates a higher preference. ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
											"target": schema.StringAttribute{
												MarkdownDescription: "Target. Hostname of the machine providing the service ves.io.schema.rules.string.pattern: ^[.]$|^([a-zA-Z0-9]{1}[a-zA-Z0-9_-]{0,62})(\\.[a-zA-Z0-9_]{1}[a-zA-Z0-9_-]{0,62})*?(\\.[a-zA-Z]{1}[a-zA-Z0-9]{0,62})\\.?$",
												Optional: true,
											},
											"weight": schema.Int64Attribute{
												MarkdownDescription: "Weight. Weight of the target. A higher number indicates a higher preference. ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 65535",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"sshfp_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS SSHFP Record. DNS SSHFP Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). SSHFP Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "SSHFP Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"algorithm": schema.StringAttribute{
												MarkdownDescription: "SSHFP Algorithm. SSHFP algorithm value must be compatible with the specified algorithm. - UNSPECIFIEDALGORITHM: UNSPECIFIEDALGORITHM - RSA: RSA - DSA: DSA - ECDSA: ECDSA - Ed25519: Ed25519 - Ed448: Ed448",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"sha1_fingerprint": schema.SingleNestedBlock{
												MarkdownDescription: "SHA1 Fingerprint.",
											},
											"sha256_fingerprint": schema.SingleNestedBlock{
												MarkdownDescription: "SHA256 Fingerprint.",
											},
										},
									},
								},
							},
						},
						"tlsa_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNS TLSA Record. DNS TLSA Record",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). TLSA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"values": schema.ListNestedBlock{
									MarkdownDescription: "TLSA Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"certificate_association_data": schema.StringAttribute{
												MarkdownDescription: "Certificate Association Data. The actual data to be matched given the settings of the other fields. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.hex: true ves.io.schema.rules.string.max_len: 4096 ves.io.schema.rules.string.min_len: 1",
												Optional: true,
											},
											"certificate_usage": schema.StringAttribute{
												MarkdownDescription: "TLSA Record Certificate Usage. - CertificateAuthorityConstraint: Certificate Authority Constraint - ServiceCertificateConstraint: Service Certificate Constraint - TrustAnchorAssertion: Trust Anchor Assertion - DomainIssuedCertificate: Domain Issued Certificate",
												Optional: true,
											},
											"matching_type": schema.StringAttribute{
												MarkdownDescription: "TLSA Record Matching Type. - NoHash: No Hash - SHA256: SHA-256 - SHA512: SHA-512",
												Optional: true,
											},
											"selector": schema.StringAttribute{
												MarkdownDescription: "TLSA Record Selector. - FullCertificate: Full Certificate - UseSubjectPublicKey: Use Subject Public Key",
												Optional: true,
											},
										},
									},
								},
							},
						},
						"txt_record": schema.SingleNestedBlock{
							MarkdownDescription: "DNSTXTResourceRecord.",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Record Name (Excluding Domain name). TXT Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
									Optional: true,
								},
								"values": schema.ListAttribute{
									MarkdownDescription: "Text. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.max_len: 4000 ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
									Optional: true,
									ElementType: types.StringType,
								},
							},
						},
					},

				},
			},
			"default_soa_parameters": schema.SingleNestedBlock{
				MarkdownDescription: "Empty. This can be used for messages where no values are needed",
			},
			"dnssec_mode": schema.SingleNestedBlock{
				MarkdownDescription: "Disable.",
				Attributes: map[string]schema.Attribute{
				},
				Blocks: map[string]schema.Block{
					"disable": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"enable": schema.SingleNestedBlock{
						MarkdownDescription: "Enable. DNSSEC enable",
					},
				},

			},
			"rr_set_group": schema.ListNestedBlock{
				MarkdownDescription: "Create and manage set groups, and resource record sets within them, x-ves-io-managed set is managed by F5. ves.io.schema.rules.repeated.max_items: 50 ves.io.schema.rules.repeated.unique_metadata_name: true",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
					},
					Blocks: map[string]schema.Block{
						"metadata": schema.SingleNestedBlock{
							MarkdownDescription: "Message Metadata. MessageMetaType is metadata (common attributes) of a message that only certain messages have. This information is propagated to the metadata of a child object that gets created from the containing message during view processing. The information in this type can be specified by user during create and replace APIs.",
							Attributes: map[string]schema.Attribute{
								"description": schema.StringAttribute{
									MarkdownDescription: "Description. Human readable description. ves.io.schema.rules.string.max_len: 256",
									Optional: true,
								},
								"name": schema.StringAttribute{
									MarkdownDescription: "Name. This is the name of the message. The value of name has to follow DNS-1035 format. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.min_len: 1 ves.io.schema.rules.string.ves_object_name: true",
									Optional: true,
								},
							},
						},
						"rr_set": schema.ListNestedBlock{
							MarkdownDescription: "Resource Record Sets. Collection of DNS resource record sets ves.io.schema.rules.repeated.max_items: 50000",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"description": schema.StringAttribute{
										MarkdownDescription: "Comment.",
										Optional: true,
									},
									"ttl": schema.Int64Attribute{
										MarkdownDescription: "Time to live. ves.io.schema.rules.uint32.gte: 60 ves.io.schema.rules.uint32.lte: 2147483647",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"a_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSAResourceRecord. A Records",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). A Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"values": schema.ListAttribute{
												MarkdownDescription: "IPv4 Addresses. A valid IPv4 address, for example: 1.1.1.1 Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.ipv4: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
												Optional: true,
												ElementType: types.StringType,
											},
										},
									},
									"aaaa_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSAAAAResourceRecord. RecordSet for AAAA Records",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). AAAA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"values": schema.ListAttribute{
												MarkdownDescription: "IPv6 Addresses. A valid IPv6 address, for example: 2001:0db8:85a3:0000:0000:8a2e:0370:7334 Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.ipv6: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
												Optional: true,
												ElementType: types.StringType,
											},
										},
									},
									"afsdb_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS AFSDB Record. DNS AFSDB Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). AFSDB Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "AFSDB Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"alias_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSAliasResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"value": schema.StringAttribute{
												MarkdownDescription: "Domain. A valid domain name, for example: example.com ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 255",
												Optional: true,
											},
										},
									},
									"caa_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSCAAResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). CAA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "CAA Record Value. ves.io.schema.rules.repeated.max_items: 100",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"cds_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS CDS Record. DNS CDS Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). CDS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "DS Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"cert_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS CERT Record. DNS CERT Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). CERT Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "CERT Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"cname_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSCNAMEResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). CName Record name, please provide only the specific subdomain or record name without the base domain. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.pattern: ^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "Domain. ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 255",
												Optional: true,
											},
										},
									},
									"ds_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS DS Record. DNS DS Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). DS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "DS Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"eui48_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS EUI48 Record. DNS EUI48 Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). EUI48 Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "EUI48 Identifier. A valid eui48 identifier, for example: 01-23-45-67-89-ab Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 17 ves.io.schema.rules.string.min_len: 17 ves.io.schema.rules.string.pattern: ^([0-9A-Fa-f]{2}-){5}([0-9A-Fa-f]{2})$",
												Optional: true,
											},
										},
									},
									"eui64_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS EUI64 Record. DNS EUI64 Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). EUI64 Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
											"value": schema.StringAttribute{
												MarkdownDescription: "EUI64 Identifier. A valid EUI64 identifier, for example: 01-23-45-67-89-ab-cd-ef Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 23 ves.io.schema.rules.string.min_len: 23 ves.io.schema.rules.string.pattern: ^([0-9A-Fa-f]{2}-){7}([0-9A-Fa-f]{2})$",
												Optional: true,
											},
										},
									},
									"lb_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS Load Balancer Record. DNS Load Balancer Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). Load Balancer record name (except for SRV DNS Load balancer record) should be a simple record name and not a subdomain of a subdomain. ves.io.schema.rules.string.max_len: 255",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"value": schema.SingleNestedBlock{
												MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
											},
										},
									},
									"loc_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS LOC Record. DNS LOC Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). LOC Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "LOC Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"mx_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSMXResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). MX Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "MX Record Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"naptr_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS NAPTR Record. DNS NAPTR Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). NAPTR Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "NAPTR Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"ns_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSNSResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). NS Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"values": schema.ListAttribute{
												MarkdownDescription: "Name Servers. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.hostname: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
												Optional: true,
												ElementType: types.StringType,
											},
										},
									},
									"ptr_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSPTRResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). PTR Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"values": schema.ListAttribute{
												MarkdownDescription: "Domain Name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.hostname: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
												Optional: true,
												ElementType: types.StringType,
											},
										},
									},
									"srv_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSSRVResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). SRV Record name, please provide only the specific subdomain or record name without the base domain. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.pattern: ^([*]|[a-zA-Z0-9-_]{1,63})([.][a-zA-Z0-9-_]{1,63})*$",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "SRV Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"sshfp_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS SSHFP Record. DNS SSHFP Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). SSHFP Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "SSHFP Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"tlsa_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNS TLSA Record. DNS TLSA Record",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). TLSA Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^([a-zA-Z0-9*?]|([a-zA-Z0-9?*]+-[a-zA-Z0-9*?]+)){0,253}",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"values": schema.ListNestedBlock{
												MarkdownDescription: "TLSA Value. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
									"txt_record": schema.SingleNestedBlock{
										MarkdownDescription: "DNSTXTResourceRecord.",
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												MarkdownDescription: "Record Name (Excluding Domain name). TXT Record name, please provide only the specific subdomain or record name without the base domain. ves.io.schema.rules.string.pattern: ^$|^([*]|[a-zA-Z0-9-/_]{1,63})([.][a-zA-Z0-9-/_]{1,63})*$",
												Optional: true,
											},
											"values": schema.ListAttribute{
												MarkdownDescription: "Text. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.max_len: 4000 ves.io.schema.rules.repeated.max_items: 100 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
												Optional: true,
												ElementType: types.StringType,
											},
										},
									},
								},
							},
						},
					},

				},
			},
			"soa_parameters": schema.SingleNestedBlock{
				MarkdownDescription: "SOARecordParameterConfig.",
				Attributes: map[string]schema.Attribute{
					"expire": schema.Int64Attribute{
						MarkdownDescription: "Expire. expire value indicates when secondary nameservers should stop answering request for this zone if primary does not respond ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 2147483647",
						Optional: true,
					},
					"negative_ttl": schema.Int64Attribute{
						MarkdownDescription: "Negative TTL. negative ttl value indicates how long to cache non-existent resource record for this zone ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 2147483647",
						Optional: true,
					},
					"refresh": schema.Int64Attribute{
						MarkdownDescription: "Refresh interval. refresh value indicates when secondary nameservers should query for the SOA record to detect zone changes ves.io.schema.rules.uint32.gte: 3600 ves.io.schema.rules.uint32.lte: 2147483647",
						Optional: true,
					},
					"retry": schema.Int64Attribute{
						MarkdownDescription: "Retry Interval. retry value indicates when secondary nameservers should retry to request the serial number if primary does not respond ves.io.schema.rules.uint32.gte: 60 ves.io.schema.rules.uint32.lte: 2147483647",
						Optional: true,
					},
					"ttl": schema.Int64Attribute{
						MarkdownDescription: "TTL. SOA record time to live (in seconds) ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 2147483647",
						Optional: true,
					},
				},

			},
		},
	}
}

func (r *DNSZoneResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *DNSZoneResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data DNSZoneResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.DNSZone{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.DNSZoneSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	created, err := r.client.CreateDNSZone(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create DNSZone: %s", err))
		return
	}

	data.ID = types.StringValue(created.Metadata.Name)
	tflog.Trace(ctx, "created DNSZone resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DNSZoneResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data DNSZoneResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource, err := r.client.GetDNSZone(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read DNSZone: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	if len(apiResource.Metadata.Labels) > 0 {
		labels, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Labels)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Labels = labels
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DNSZoneResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data DNSZoneResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.DNSZone{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.DNSZoneSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	updated, err := r.client.UpdateDNSZone(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update DNSZone: %s", err))
		return
	}

	data.ID = types.StringValue(updated.Metadata.Name)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *DNSZoneResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data DNSZoneResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteDNSZone(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete DNSZone: %s", err))
		return
	}
}

func (r *DNSZoneResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
