// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
)

var (
	_ resource.Resource                = &NetworkInterfaceResource{}
	_ resource.ResourceWithConfigure   = &NetworkInterfaceResource{}
	_ resource.ResourceWithImportState = &NetworkInterfaceResource{}
)

func NewNetworkInterfaceResource() resource.Resource {
	return &NetworkInterfaceResource{}
}

type NetworkInterfaceResource struct {
	client *client.Client
}

type NetworkInterfaceResourceModel struct {
	Name types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Labels types.Map `tfsdk:"labels"`
	Annotations types.Map `tfsdk:"annotations"`
	ID types.String `tfsdk:"id"`
}

func (r *NetworkInterfaceResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_network_interface"
}

func (r *NetworkInterfaceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Network interface represents configuration of a network device. It is created by users in system namespace.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the NetworkInterface. Must be unique within the namespace.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the NetworkInterface will be created.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"dedicated_interface": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: dedicated_interface, dedicated_management_interface, ethernet_interface, layer2_interface, tunnel_interface] Dedicated Interface. Dedicated Interface Configuration",
				Attributes: map[string]schema.Attribute{
					"device": schema.StringAttribute{
						MarkdownDescription: "Interface Device. Name of the device for which interface is configured. Use wwan0 for 4G/LTE. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"mtu": schema.Int64Attribute{
						MarkdownDescription: "Maximum Packet Size (MTU). Maximum packet size (Maximum Transfer Unit) of the interface When configured, mtu must be between 512 and 16384 ves.io.schema.rules.uint32.ranges: 0,512-16384",
						Optional: true,
					},
					"node": schema.StringAttribute{
						MarkdownDescription: "Specific Node. Exclusive with [cluster] Configuration will apply to a device on the given node of the site. ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"priority": schema.Int64Attribute{
						MarkdownDescription: "Priority. Priority of the network interface when multiple network interfaces are present in outside network Greater the value, higher the priority ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 255",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"cluster": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"is_primary": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"monitor": schema.SingleNestedBlock{
						MarkdownDescription: "Link Quality Monitoring Configuration. Link Quality Monitoring configuration for a network interface.",
					},
					"monitor_disabled": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"not_primary": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
			"dedicated_management_interface": schema.SingleNestedBlock{
				MarkdownDescription: "Dedicated Management Interface. Dedicated Interface Configuration",
				Attributes: map[string]schema.Attribute{
					"device": schema.StringAttribute{
						MarkdownDescription: "Interface Device. Name of the device for which interface is configured Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"mtu": schema.Int64Attribute{
						MarkdownDescription: "Maximum Packet Size (MTU). Maximum packet size (Maximum Transfer Unit) of the interface When configured, mtu must be between 512 and 16384 ves.io.schema.rules.uint32.ranges: 0,512-16384",
						Optional: true,
					},
					"node": schema.StringAttribute{
						MarkdownDescription: "Specific Node. Exclusive with [cluster] Configuration will apply to a device on the given node of the site. ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"cluster": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
			"ethernet_interface": schema.SingleNestedBlock{
				MarkdownDescription: "Ethernet Interface. Ethernet Interface Configuration",
				Attributes: map[string]schema.Attribute{
					"device": schema.StringAttribute{
						MarkdownDescription: "Ethernet Device. Interface configuration for the ethernet device Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"mtu": schema.Int64Attribute{
						MarkdownDescription: "Maximum Packet Size (MTU). Maximum packet size (Maximum Transfer Unit) of the interface When configured, mtu must be between 512 and 16384 ves.io.schema.rules.uint32.ranges: 0,512-16384",
						Optional: true,
					},
					"node": schema.StringAttribute{
						MarkdownDescription: "Specific Node. Exclusive with [cluster] Configuration will apply to a device on the given node. ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"priority": schema.Int64Attribute{
						MarkdownDescription: "Priority. Priority of the network interface when multiple network interfaces are present in outside network Greater the value, higher the priority ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 255",
						Optional: true,
					},
					"vlan_id": schema.Int64Attribute{
						MarkdownDescription: "VLAN Id. Exclusive with [untagged] Configure a VLAN tagged ethernet interface ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 4095",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"cluster": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"dhcp_client": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"dhcp_server": schema.SingleNestedBlock{
						MarkdownDescription: "DHCPServerParametersType.",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"automatic_from_end": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"automatic_from_start": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"dhcp_networks": schema.ListNestedBlock{
								MarkdownDescription: "DHCP Networks. List of networks from which DHCP Server can allocate IPv4 Addresses Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 1 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"dgw_address": schema.StringAttribute{
											MarkdownDescription: "Static IPv4 Configuration. Exclusive with [first_address last_address] Enter a IPv4 address from the network prefix to be used as the default gateway. ves.io.schema.rules.string.ipv4: true",
											Optional: true,
										},
										"dns_address": schema.StringAttribute{
											MarkdownDescription: "Static IPv4 Configuration. Exclusive with [same_as_dgw] Enter a IPv4 address from the network prefix to be used as the DNS server. ves.io.schema.rules.string.ipv4: true",
											Optional: true,
										},
										"network_prefix": schema.StringAttribute{
											MarkdownDescription: "Network Prefix. Exclusive with [] Set the network prefix for the site. ex: 10.1.1.0/24 ves.io.schema.rules.string.ipv4_prefix: true",
											Optional: true,
										},
										"pool_settings": schema.StringAttribute{
											MarkdownDescription: "Interface Network Type. Identifies the how to pick the network for Interface. Address ranges in DHCP pool list are used for IP Address allocation Address ranges in DHCP pool list are excluded from IP Address allocation",
											Optional: true,
										},
									},
									Blocks: map[string]schema.Block{
										"first_address": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"last_address": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"pools": schema.ListNestedBlock{
											MarkdownDescription: "DHCP Pools. List of non overlapping ip address ranges. ves.io.schema.rules.repeated.max_items: 16 ves.io.schema.rules.repeated.unique: true",
											NestedObject: schema.NestedBlockObject{
												Attributes: map[string]schema.Attribute{},
											},
										},
										"same_as_dgw": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
									},
								},
							},
							"fixed_ip_map": schema.SingleNestedBlock{
								MarkdownDescription: "Fixed MAC Address to IPv4 Assignments. Assign fixed IPv4 addresses based on the MAC Address of the DHCP Client. ves.io.schema.rules.map.keys.string.mac: true ves.io.schema.rules.map.max_pairs: 128 ves.io.schema.rules.map.unique_values: true ves.io.schema.rules.map.values.string.ipv4: true",
							},
							"interface_ip_map": schema.SingleNestedBlock{
								MarkdownDescription: "Interface IPv4 Assignments. Specify static IPv4 addresses per node.",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"interface_ip_map": schema.SingleNestedBlock{
										MarkdownDescription: "Site:Node to IPv4 Address Mapping. Specify static IPv4 addresses per site:node. ves.io.schema.rules.map.keys.string.max_len: 128 ves.io.schema.rules.map.keys.string.min_len: 1 ves.io.schema.rules.map.max_pairs: 64 ves.io.schema.rules.map.values.string.ipv4: true",
									},
								},
							},
						},
					},
					"ipv6_auto_config": schema.SingleNestedBlock{
						MarkdownDescription: "IPV6AutoConfigType.",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"host": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"router": schema.SingleNestedBlock{
								MarkdownDescription: "IPV6AutoConfigRouterType.",
								Attributes: map[string]schema.Attribute{
									"network_prefix": schema.StringAttribute{
										MarkdownDescription: "Network Prefix. Exclusive with [stateful] Nework prefix that is used as Prefix information Allowed only /64 prefix length as per RFC 4862 ves.io.schema.rules.string.ipv6_prefix: true ves.io.schema.rules.string.pattern: .*::/64$",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"dns_config": schema.SingleNestedBlock{
										MarkdownDescription: "IPV6DnsConfig.",
									},
									"stateful": schema.SingleNestedBlock{
										MarkdownDescription: "DHCPIPV6 Stateful Server.",
									},
								},
							},
						},
					},
					"is_primary": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"monitor": schema.SingleNestedBlock{
						MarkdownDescription: "Link Quality Monitoring Configuration. Link Quality Monitoring configuration for a network interface.",
					},
					"monitor_disabled": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"no_ipv6_address": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"not_primary": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"site_local_inside_network": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"site_local_network": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"static_ip": schema.SingleNestedBlock{
						MarkdownDescription: "Static IP Parameters. Configure Static IP parameters",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"cluster_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Cluster: Static IP Parameters. Configure Static IP parameters for cluster",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"interface_ip_map": schema.SingleNestedBlock{
										MarkdownDescription: "Node to IP Mapping. Map of Node to Static ip configuration value, Key:Node, Value:IP Address ves.io.schema.rules.map.keys.string.max_len: 128 ves.io.schema.rules.map.keys.string.min_len: 1 ves.io.schema.rules.map.max_pairs: 128",
									},
								},
							},
							"node_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Node: Static IP Parameters. Configure Static IP parameters for a node",
								Attributes: map[string]schema.Attribute{
									"default_gw": schema.StringAttribute{
										MarkdownDescription: "Default Gateway. IP address of the default gateway. ves.io.schema.rules.string.ip: true",
										Optional: true,
									},
									"ip_address": schema.StringAttribute{
										MarkdownDescription: "IP address/Prefix Length. IP address of the interface and prefix length Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.ip_prefix: true",
										Optional: true,
									},
								},
							},
						},
					},
					"static_ipv6_address": schema.SingleNestedBlock{
						MarkdownDescription: "Static IP Parameters. Configure Static IP parameters",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"cluster_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Cluster: Static IP Parameters. Configure Static IP parameters for cluster",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"interface_ip_map": schema.SingleNestedBlock{
										MarkdownDescription: "Node to IP Mapping. Map of Node to Static ip configuration value, Key:Node, Value:IP Address ves.io.schema.rules.map.keys.string.max_len: 128 ves.io.schema.rules.map.keys.string.min_len: 1 ves.io.schema.rules.map.max_pairs: 128",
									},
								},
							},
							"node_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Node: Static IP Parameters. Configure Static IP parameters for a node",
								Attributes: map[string]schema.Attribute{
									"default_gw": schema.StringAttribute{
										MarkdownDescription: "Default Gateway. IP address of the default gateway. ves.io.schema.rules.string.ip: true",
										Optional: true,
									},
									"ip_address": schema.StringAttribute{
										MarkdownDescription: "IP address/Prefix Length. IP address of the interface and prefix length Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.ip_prefix: true",
										Optional: true,
									},
								},
							},
						},
					},
					"storage_network": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"untagged": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
			"layer2_interface": schema.SingleNestedBlock{
				MarkdownDescription: "Layer2 Interface. Layer2 Interface Configuration",
				Attributes: map[string]schema.Attribute{
				},
				Blocks: map[string]schema.Block{
					"l2sriov_interface": schema.SingleNestedBlock{
						MarkdownDescription: "Layer2 SR-IOV Interface. Layer2 SR-IOV Interface Configuration",
						Attributes: map[string]schema.Attribute{
							"device": schema.StringAttribute{
								MarkdownDescription: "Ethernet Device. Physical ethernet interface Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
								Optional: true,
							},
							"vlan_id": schema.Int64Attribute{
								MarkdownDescription: "VLAN Id. Exclusive with [untagged] Configure a VLAN tagged interface ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 4095",
								Optional: true,
							},
						},
						Blocks: map[string]schema.Block{
							"untagged": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
						},
					},
					"l2vlan_interface": schema.SingleNestedBlock{
						MarkdownDescription: "Layer2 VLAN Interface. Layer2 VLAN Interface Configuration",
						Attributes: map[string]schema.Attribute{
							"device": schema.StringAttribute{
								MarkdownDescription: "Ethernet Device. Physical ethernet interface Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
								Optional: true,
							},
							"vlan_id": schema.Int64Attribute{
								MarkdownDescription: "VLAN Id. VLAN Id Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 4095",
								Optional: true,
							},
						},
					},
					"l2vlan_slo_interface": schema.SingleNestedBlock{
						MarkdownDescription: "VLAN on Site Local Outside Interface. Layer2 Site Local Outside VLAN Interface Configuration",
						Attributes: map[string]schema.Attribute{
							"vlan_id": schema.Int64Attribute{
								MarkdownDescription: "VLAN Id. VLAN Id Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 4095",
								Optional: true,
							},
						},
					},
				},

			},
			"tunnel_interface": schema.SingleNestedBlock{
				MarkdownDescription: "Tunnel Interface. Tunnel Interface Configuration",
				Attributes: map[string]schema.Attribute{
					"mtu": schema.Int64Attribute{
						MarkdownDescription: "Maximum Packet Size (MTU). Maximum packet size (Maximum Transfer Unit) of the interface When configured, mtu must be between 512 and 16384 ves.io.schema.rules.uint32.ranges: 0,512-16384",
						Optional: true,
					},
					"node": schema.StringAttribute{
						MarkdownDescription: "Specific Node. Exclusive with [] Configuration will apply to a given device on the given node. ves.io.schema.rules.string.max_len: 64 ves.io.schema.rules.string.min_len: 1",
						Optional: true,
					},
					"priority": schema.Int64Attribute{
						MarkdownDescription: "Priority. Priority of the network interface when multiple network interfaces are present in outside network Greater the value, higher the priority ves.io.schema.rules.uint32.gte: 0 ves.io.schema.rules.uint32.lte: 255",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"site_local_inside_network": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"site_local_network": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"static_ip": schema.SingleNestedBlock{
						MarkdownDescription: "Static IP Parameters. Configure Static IP parameters",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"cluster_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Cluster: Static IP Parameters. Configure Static IP parameters for cluster",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"interface_ip_map": schema.SingleNestedBlock{
										MarkdownDescription: "Node to IP Mapping. Map of Node to Static ip configuration value, Key:Node, Value:IP Address ves.io.schema.rules.map.keys.string.max_len: 128 ves.io.schema.rules.map.keys.string.min_len: 1 ves.io.schema.rules.map.max_pairs: 128",
									},
								},
							},
							"node_static_ip": schema.SingleNestedBlock{
								MarkdownDescription: "Node: Static IP Parameters. Configure Static IP parameters for a node",
								Attributes: map[string]schema.Attribute{
									"default_gw": schema.StringAttribute{
										MarkdownDescription: "Default Gateway. IP address of the default gateway. ves.io.schema.rules.string.ip: true",
										Optional: true,
									},
									"ip_address": schema.StringAttribute{
										MarkdownDescription: "IP address/Prefix Length. IP address of the interface and prefix length Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.ip_prefix: true",
										Optional: true,
									},
								},
							},
						},
					},
					"tunnel": schema.SingleNestedBlock{
						MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
								Optional: true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
								Optional: true,
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
								Optional: true,
							},
						},
					},
				},

			},
		},
	}
}

func (r *NetworkInterfaceResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *NetworkInterfaceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data NetworkInterfaceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.NetworkInterface{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.NetworkInterfaceSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	created, err := r.client.CreateNetworkInterface(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create NetworkInterface: %s", err))
		return
	}

	data.ID = types.StringValue(created.Metadata.Name)
	tflog.Trace(ctx, "created NetworkInterface resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *NetworkInterfaceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data NetworkInterfaceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource, err := r.client.GetNetworkInterface(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read NetworkInterface: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	if len(apiResource.Metadata.Labels) > 0 {
		labels, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Labels)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Labels = labels
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *NetworkInterfaceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data NetworkInterfaceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.NetworkInterface{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.NetworkInterfaceSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	updated, err := r.client.UpdateNetworkInterface(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update NetworkInterface: %s", err))
		return
	}

	data.ID = types.StringValue(updated.Metadata.Name)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *NetworkInterfaceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data NetworkInterfaceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteNetworkInterface(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete NetworkInterface: %s", err))
		return
	}
}

func (r *NetworkInterfaceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
