// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
)

var (
	_ resource.Resource                = &OriginPoolResource{}
	_ resource.ResourceWithConfigure   = &OriginPoolResource{}
	_ resource.ResourceWithImportState = &OriginPoolResource{}
)

func NewOriginPoolResource() resource.Resource {
	return &OriginPoolResource{}
}

type OriginPoolResource struct {
	client *client.Client
}

type OriginPoolResourceModel struct {
	Name types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Labels types.Map `tfsdk:"labels"`
	Annotations types.Map `tfsdk:"annotations"`
	ID types.String `tfsdk:"id"`
	EndpointSelection types.String `tfsdk:"endpoint_selection"`
	HealthCheckPort types.Int64 `tfsdk:"health_check_port"`
	LoadBalancerAlgorithm types.String `tfsdk:"loadbalancer_algorithm"`
	Port types.Int64 `tfsdk:"port"`
}

func (r *OriginPoolResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_origin_pool"
}

func (r *OriginPoolResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Shape of the origin pool create specification",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the OriginPool. Must be unique within the namespace.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the OriginPool will be created.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"endpoint_selection": schema.StringAttribute{
				MarkdownDescription: "Endpoint Selection Policy. Policy for selection of endpoints from local site/remote site/both Consider both remote and local endpoints for load balancing LOCAL_ONLY: Consider only local endpoints for load balancing Enable this policy to load balance ONLY among locally discovered endpoints Prefer the local endpoints for load balancing. If local endpoints are not present remote endpoints will be considered.",
				Optional: true,
			},
			"health_check_port": schema.Int64Attribute{
				MarkdownDescription: "[OneOf: health_check_port, same_as_endpoint_port] Health check port. Exclusive with [same_as_endpoint_port] Port used for performing health check ves.io.schema.rules.uint32.lte: 65535",
				Optional: true,
			},
			"loadbalancer_algorithm": schema.StringAttribute{
				MarkdownDescription: "Load Balancer Algorithm. Different load balancing algorithms supported When a connection to a endpoint in an upstream cluster is required, the load balancer uses loadbalancer_algorithm to determine which host is selected. - ROUND_ROBIN: ROUND_ROBIN Policy in which each healthy/available upstream endpoint is selected in round robin order. - LEAST_REQUEST: LEAST_REQUEST Policy in which loadbalancer picks the upstream endpoint which has the fewest active requests - RING_HASH: RING_HASH Policy im...",
				Optional: true,
			},
			"port": schema.Int64Attribute{
				MarkdownDescription: "Port. Exclusive with [automatic_port lb_port] Endpoint service is available on this port ves.io.schema.rules.uint32.gte: 1 ves.io.schema.rules.uint32.lte: 65535",
				Optional: true,
			},
		},
		Blocks: map[string]schema.Block{
			"advanced_options": schema.SingleNestedBlock{
				MarkdownDescription: "Origin Pool Advanced Options. Configure Advanced options for origin pool",
				Attributes: map[string]schema.Attribute{
					"connection_timeout": schema.Int64Attribute{
						MarkdownDescription: "Connection Timeout. The timeout for new network connections to endpoints in the cluster. This is specified in milliseconds. The default value is 2 seconds ves.io.schema.rules.uint32.lte: 1800000",
						Optional: true,
					},
					"http_idle_timeout": schema.Int64Attribute{
						MarkdownDescription: "HTTP Idle Timeout. The idle timeout for upstream connection pool connections. The idle timeout is defined as the period in which there are no active requests. When the idle timeout is reached the connection will be closed. Note that request based timeouts mean that HTTP/2 PINGs will not keep the connection alive. This is specified in milliseconds. The default value is 5 minutes. ves.io.schema.rules.uint32.lte: 600000",
						Optional: true,
					},
					"panic_threshold": schema.Int64Attribute{
						MarkdownDescription: "Panic threshold. Exclusive with [no_panic_threshold] x-example:'25' Configure a threshold (percentage of unhealthy endpoints) below which all endpoints will be considered for load balancing ignoring its health status. ves.io.schema.rules.uint32.lte: 100",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"auto_http_config": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"circuit_breaker": schema.SingleNestedBlock{
						MarkdownDescription: "Circuit Breaker. CircuitBreaker provides a mechanism for watching failures in upstream connections or requests and if the failures reach a certain threshold, automatically fail subsequent requests which allows to apply back pressure on downstream quickly.",
						Attributes: map[string]schema.Attribute{
							"connection_limit": schema.Int64Attribute{
								MarkdownDescription: "Connection Limit. The maximum number of connections that loadbalancer will establish to all hosts in an upstream cluster. In practice this is only applicable to TCP and HTTP/1.1 clusters since HTTP/2 uses a single connection to each host. Remove endpoint out of load balancing decision, if number of connections reach connection limit. ves.io.schema.rules.uint32.lte: 32768",
								Optional: true,
							},
							"max_requests": schema.Int64Attribute{
								MarkdownDescription: "Maximum Request Count. The maximum number of requests that can be outstanding to all hosts in a cluster at any given time. In practice this is applicable to HTTP/2 clusters since HTTP/1.1 clusters are governed by the maximum connections (connection_limit). Remove endpoint out of load balancing decision, if requests exceed this count. ves.io.schema.rules.uint32.lte: 32768",
								Optional: true,
							},
							"pending_requests": schema.Int64Attribute{
								MarkdownDescription: "Pending Requests. The maximum number of requests that will be queued while waiting for a ready connection pool connection. Since HTTP/2 requests are sent over a single connection, this circuit breaker only comes into play as the initial connection is created, as requests will be multiplexed immediately afterwards. For HTTP/1.1, requests are added to the list of pending requests whenever there aren’t enough upstream connections available to immediately dispatch the request, so this circuit b...",
								Optional: true,
							},
							"priority": schema.StringAttribute{
								MarkdownDescription: "Routing Priority. Priority routing for each request. Different connection pools are used based on the priority selected for the request. Also, circuit-breaker configuration at destination cluster is chosen based on selected priority. Default routing mechanism High-Priority routing mechanism",
								Optional: true,
							},
							"retries": schema.Int64Attribute{
								MarkdownDescription: "Retry Count. The maximum number of retries that can be outstanding to all hosts in a cluster at any given time. Remove endpoint out of load balancing decision, if retries for request exceed this count. ves.io.schema.rules.uint32.lte: 32768",
								Optional: true,
							},
						},
					},
					"default_circuit_breaker": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_circuit_breaker": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_lb_source_ip_persistance": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_outlier_detection": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_proxy_protocol": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_subsets": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"enable_lb_source_ip_persistance": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"enable_subsets": schema.SingleNestedBlock{
						MarkdownDescription: "Origin Pool Subset Options. Configure subset options for origin pool",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"any_endpoint": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"default_subset": schema.SingleNestedBlock{
								MarkdownDescription: "Origin Pool Default Subset. Default Subset definition",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"default_subset": schema.SingleNestedBlock{
										MarkdownDescription: "Default Subset for Origin Pool. List of key-value pairs that define default subset. which gets used when route specifies no metadata or no subset matching the metadata exists. ves.io.schema.rules.map.max_pairs: 32",
									},
								},
							},
							"endpoint_subsets": schema.ListNestedBlock{
								MarkdownDescription: "Origin Server Subsets Classes. List of subset class. Subsets class is defined using list of keys. Every unique combination of values of these keys form a subset withing the class. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 32",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"keys": schema.ListAttribute{
											MarkdownDescription: "Keys. List of keys that define a cluster subset class. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.items.string.not_empty: true ves.io.schema.rules.repeated.max_items: 16",
											Optional: true,
											ElementType: types.StringType,
										},
									},
								},
							},
							"fail_request": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
						},
					},
					"http1_config": schema.SingleNestedBlock{
						MarkdownDescription: "HTTP/1.1 Protocol Options. HTTP/1.1 Protocol options for upstream connections",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"header_transformation": schema.SingleNestedBlock{
								MarkdownDescription: "Header Transformation. Header Transformation options for HTTP/1.1 request/response headers",
								Attributes: map[string]schema.Attribute{
								},
								Blocks: map[string]schema.Block{
									"default_header_transformation": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"legacy_header_transformation": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"preserve_case_header_transformation": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"proper_case_header_transformation": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
								},
							},
						},
					},
					"http2_options": schema.SingleNestedBlock{
						MarkdownDescription: "Http2 Protocol Options. Http2 Protocol options for upstream connections",
						Attributes: map[string]schema.Attribute{
							"enabled": schema.BoolAttribute{
								MarkdownDescription: "HTTP2 Enabled. Enable/disable HTTP2 Protocol for upstream connections",
								Optional: true,
							},
						},
					},
					"no_panic_threshold": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"outlier_detection": schema.SingleNestedBlock{
						MarkdownDescription: "Outlier Detection. Outlier detection and ejection is the process of dynamically determining whether some number of hosts in an upstream cluster are performing unlike the others and removing them from the healthy load balancing set. Outlier detection is a form of passive health checking. Algorithm 1. A endpoint is determined to be an outlier (based on configured number of consecutive_5xx or consecutive_gateway_failures) . 2. If no endpoints have been ejected, loadbalancer will eject the host i...",
						Attributes: map[string]schema.Attribute{
							"base_ejection_time": schema.Int64Attribute{
								MarkdownDescription: "Base Ejection Time. The base time that a host is ejected for. The real time is equal to the base time multiplied by the number of times the host has been ejected. This causes hosts to get ejected for longer periods if they continue to fail. Defaults to 30000ms or 30s. Specified in milliseconds. ves.io.schema.rules.uint32.lte: 1800000",
								Optional: true,
							},
							"consecutive_5xx": schema.Int64Attribute{
								MarkdownDescription: "Consecutive 5xx Count. If an upstream endpoint returns some number of consecutive 5xx, it will be ejected. Note that in this case a 5xx means an actual 5xx respond code, or an event that would cause the HTTP router to return one on the upstream’s behalf(reset, connection failure, etc.) consecutive_5xx indicates the number of consecutive 5xx responses required before a consecutive 5xx ejection occurs. Defaults to 5. ves.io.schema.rules.uint32.lte: 1024",
								Optional: true,
							},
							"consecutive_gateway_failure": schema.Int64Attribute{
								MarkdownDescription: "Consecutive Gateway Failure. If an upstream endpoint returns some number of consecutive “gateway errors” (502, 503 or 504 status code), it will be ejected. Note that this includes events that would cause the HTTP router to return one of these status codes on the upstream’s behalf (reset, connection failure, etc.). consecutive_gateway_failure indicates the number of consecutive gateway failures before a consecutive gateway failure ejection occurs. Defaults to 5. ves.io.schema.rules.uint3...",
								Optional: true,
							},
							"interval": schema.Int64Attribute{
								MarkdownDescription: "Interval. The time interval between ejection analysis sweeps. This can result in both new ejections as well as endpoints being returned to service. Defaults to 10000ms or 10s. Specified in milliseconds. ves.io.schema.rules.uint32.lte: 600000",
								Optional: true,
							},
							"max_ejection_percent": schema.Int64Attribute{
								MarkdownDescription: "Max Ejection Percentage. The maximum % of an upstream cluster that can be ejected due to outlier detection. Defaults to 10% but will eject at least one host regardless of the value. ves.io.schema.rules.uint32.lte: 100",
								Optional: true,
							},
						},
					},
					"proxy_protocol_v1": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"proxy_protocol_v2": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
			"automatic_port": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: automatic_port, lb_port, port] Empty. This can be used for messages where no values are needed",
			},
			"healthcheck": schema.ListNestedBlock{
				MarkdownDescription: "Health Check object. Reference to healthcheck configuration objects ves.io.schema.rules.repeated.max_items: 4",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
							Optional: true,
						},
						"namespace": schema.StringAttribute{
							MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
							Optional: true,
						},
						"tenant": schema.StringAttribute{
							MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
							Optional: true,
						},
					},

				},
			},
			"lb_port": schema.SingleNestedBlock{
				MarkdownDescription: "Empty. This can be used for messages where no values are needed",
			},
			"no_tls": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: no_tls, use_tls] Empty. This can be used for messages where no values are needed",
			},
			"origin_servers": schema.ListNestedBlock{
				MarkdownDescription: "Origin Servers. List of origin servers in this pool Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 32 ves.io.schema.rules.repeated.min_items: 1 ves.io.schema.rules.repeated.unique: true",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
					},
					Blocks: map[string]schema.Block{
						"cbip_service": schema.SingleNestedBlock{
							MarkdownDescription: "Discovered Classic BIG-IP Service Name. Specify origin server with Classic BIG-IP Service (Virtual Server)",
							Attributes: map[string]schema.Attribute{
								"service_name": schema.StringAttribute{
									MarkdownDescription: "Service Name. Name of the discovered Classic BIG-IP virtual server to be used as origin. Required: YES ves.io.schema.rules.message.required: true",
									Optional: true,
								},
							},
						},
						"consul_service": schema.SingleNestedBlock{
							MarkdownDescription: "Consul Service Name on given Sites. Specify origin server with Hashi Corp Consul service name and site information",
							Attributes: map[string]schema.Attribute{
								"service_name": schema.StringAttribute{
									MarkdownDescription: "Service Name. Consul service name of this origin server will be listed, including cluster-id. The format is servicename:cluster-id. Required: YES ves.io.schema.rules.message.required: true",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"inside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"outside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"site_locator": schema.SingleNestedBlock{
									MarkdownDescription: "Site or Virtual Site. This message defines a reference to a site or virtual site object",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
										"virtual_site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
									},
								},
								"snat_pool": schema.SingleNestedBlock{
									MarkdownDescription: "Snat Pool. Snat Pool configuration",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"no_snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "IPv4 Prefix List. x-example: '192.168.20.0/24' List of IPv4 prefixes that represent an endpoint",
										},
									},
								},
							},
						},
						"custom_endpoint_object": schema.SingleNestedBlock{
							MarkdownDescription: "Custom Endpoint Object for Origin Server. Specify origin server with a reference to endpoint object",
							Attributes: map[string]schema.Attribute{
							},
							Blocks: map[string]schema.Block{
								"endpoint": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
							},
						},
						"k8s_service": schema.SingleNestedBlock{
							MarkdownDescription: "K8s Service Name on given Sites. Specify origin server with K8s service name and site information",
							Attributes: map[string]schema.Attribute{
								"protocol": schema.StringAttribute{
									MarkdownDescription: "Protocol Type. Type of protocol - PROTOCOL_TCP: TCP - PROTOCOL_UDP: UDP",
									Optional: true,
								},
								"service_name": schema.StringAttribute{
									MarkdownDescription: "Service Name. Exclusive with [] K8s service name of the origin server will be listed, including the namespace and cluster-id. For vK8s services, you need to enter a string with the format servicename.namespace:cluster-id. If the servicename is 'frontend', namespace is 'speedtest' and cluster-id is 'prod', then you will enter 'frontend.speedtest:prod'. Both namespace and cluster-id are optional. ves.io.schema.rules.string.ves_service_namespace_name: true",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"inside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"outside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"site_locator": schema.SingleNestedBlock{
									MarkdownDescription: "Site or Virtual Site. This message defines a reference to a site or virtual site object",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
										"virtual_site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
									},
								},
								"snat_pool": schema.SingleNestedBlock{
									MarkdownDescription: "Snat Pool. Snat Pool configuration",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"no_snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "IPv4 Prefix List. x-example: '192.168.20.0/24' List of IPv4 prefixes that represent an endpoint",
										},
									},
								},
								"vk8s_networks": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
							},
						},
						"labels": schema.SingleNestedBlock{
							MarkdownDescription: "Origin Server Labels. Add Labels for this origin server, these labels can be used to form subset.",
						},
						"private_ip": schema.SingleNestedBlock{
							MarkdownDescription: "IP address on given Sites. Specify origin server with private or public IP address and site information",
							Attributes: map[string]schema.Attribute{
								"ip": schema.StringAttribute{
									MarkdownDescription: "IP. Exclusive with [] Private IPV4 address ves.io.schema.rules.string.ipv4: true",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"inside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"outside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"segment": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
								"site_locator": schema.SingleNestedBlock{
									MarkdownDescription: "Site or Virtual Site. This message defines a reference to a site or virtual site object",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
										"virtual_site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
									},
								},
								"snat_pool": schema.SingleNestedBlock{
									MarkdownDescription: "Snat Pool. Snat Pool configuration",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"no_snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "IPv4 Prefix List. x-example: '192.168.20.0/24' List of IPv4 prefixes that represent an endpoint",
										},
									},
								},
							},
						},
						"private_name": schema.SingleNestedBlock{
							MarkdownDescription: "DNS Name on given Sites. Specify origin server with private or public DNS name and site information",
							Attributes: map[string]schema.Attribute{
								"dns_name": schema.StringAttribute{
									MarkdownDescription: "DNS Name. DNS Name Required: YES ves.io.schema.rules.message.required: true",
									Optional: true,
								},
								"refresh_interval": schema.Int64Attribute{
									MarkdownDescription: "DNS Refresh Interval. Interval for DNS refresh in seconds. Max value is 7 days as per https://datatracker.ietf.org/doc/html/rfc8767 ves.io.schema.rules.uint32.ranges: 0,10-604800",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"inside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"outside_network": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"segment": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
								"site_locator": schema.SingleNestedBlock{
									MarkdownDescription: "Site or Virtual Site. This message defines a reference to a site or virtual site object",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
										"virtual_site": schema.SingleNestedBlock{
											MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
										},
									},
								},
								"snat_pool": schema.SingleNestedBlock{
									MarkdownDescription: "Snat Pool. Snat Pool configuration",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"no_snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"snat_pool": schema.SingleNestedBlock{
											MarkdownDescription: "IPv4 Prefix List. x-example: '192.168.20.0/24' List of IPv4 prefixes that represent an endpoint",
										},
									},
								},
							},
						},
						"public_ip": schema.SingleNestedBlock{
							MarkdownDescription: "Public IP. Specify origin server with public IP address",
							Attributes: map[string]schema.Attribute{
								"ip": schema.StringAttribute{
									MarkdownDescription: "Public IPV4. Exclusive with [] Public IPV4 address ves.io.schema.rules.string.ipv4: true",
									Optional: true,
								},
							},
						},
						"public_name": schema.SingleNestedBlock{
							MarkdownDescription: "Public DNS Name. Specify origin server with public DNS name",
							Attributes: map[string]schema.Attribute{
								"dns_name": schema.StringAttribute{
									MarkdownDescription: "DNS Name. DNS Name Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 256 ves.io.schema.rules.string.min_len: 1",
									Optional: true,
								},
								"refresh_interval": schema.Int64Attribute{
									MarkdownDescription: "DNS Refresh Interval. Interval for DNS refresh in seconds. Max value is 7 days as per https://datatracker.ietf.org/doc/html/rfc8767 ves.io.schema.rules.uint32.ranges: 0,10-604800",
									Optional: true,
								},
							},
						},
						"vn_private_ip": schema.SingleNestedBlock{
							MarkdownDescription: "IP address Virtual Network. Specify origin server with IP on Virtual Network",
							Attributes: map[string]schema.Attribute{
								"ip": schema.StringAttribute{
									MarkdownDescription: "IPV4. Exclusive with [] IPV4 address ves.io.schema.rules.string.ipv4: true",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"virtual_network": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
							},
						},
						"vn_private_name": schema.SingleNestedBlock{
							MarkdownDescription: "DNS Name on Virtual Network. Specify origin server with DNS name on Virtual Network",
							Attributes: map[string]schema.Attribute{
								"dns_name": schema.StringAttribute{
									MarkdownDescription: "DNS Name. DNS Name Required: YES ves.io.schema.rules.message.required: true",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"private_network": schema.SingleNestedBlock{
									MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"namespace": schema.StringAttribute{
											MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
										"tenant": schema.StringAttribute{
											MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
											Optional: true,
										},
									},
								},
							},
						},
					},

				},
			},
			"same_as_endpoint_port": schema.SingleNestedBlock{
				MarkdownDescription: "Empty. This can be used for messages where no values are needed",
			},
			"upstream_conn_pool_reuse_type": schema.SingleNestedBlock{
				MarkdownDescription: "Select upstream connection pool reuse state. Select upstream connection pool reuse state for every downstream connection. This configuration choice is for HTTP(S) LB only.",
				Attributes: map[string]schema.Attribute{
				},
				Blocks: map[string]schema.Block{
					"disable_conn_pool_reuse": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"enable_conn_pool_reuse": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
			"use_tls": schema.SingleNestedBlock{
				MarkdownDescription: "TLS Parameters for Origin Servers. Upstream TLS Parameters",
				Attributes: map[string]schema.Attribute{
					"max_session_keys": schema.Int64Attribute{
						MarkdownDescription: "Max Session Keys Cached. Exclusive with [default_session_key_caching disable_session_key_caching] x-example:'25' Number of session keys that are cached. ves.io.schema.rules.uint32.gte: 2 ves.io.schema.rules.uint32.lte: 64",
						Optional: true,
					},
					"sni": schema.StringAttribute{
						MarkdownDescription: "SNI Value. Exclusive with [disable_sni use_host_header_as_sni] SNI value to be used. ves.io.schema.rules.string.hostname: true ves.io.schema.rules.string.max_len: 256",
						Optional: true,
					},
				},
				Blocks: map[string]schema.Block{
					"default_session_key_caching": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_session_key_caching": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"disable_sni": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"no_mtls": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"skip_server_verification": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"tls_config": schema.SingleNestedBlock{
						MarkdownDescription: "TLS Config. This defines various options to configure TLS configuration parameters",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"custom_security": schema.SingleNestedBlock{
								MarkdownDescription: "Custom Ciphers. This defines TLS protocol config including min/max versions and allowed ciphers",
								Attributes: map[string]schema.Attribute{
									"cipher_suites": schema.ListAttribute{
										MarkdownDescription: "Cipher Suites. The TLS listener will only support the specified cipher list. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.unique: true",
										Optional: true,
										ElementType: types.StringType,
									},
									"max_version": schema.StringAttribute{
										MarkdownDescription: "TLS Protocol. TlsProtocol is enumeration of supported TLS versions F5 Distributed Cloud will choose the optimal TLS version.",
										Optional: true,
									},
									"min_version": schema.StringAttribute{
										MarkdownDescription: "TLS Protocol. TlsProtocol is enumeration of supported TLS versions F5 Distributed Cloud will choose the optimal TLS version.",
										Optional: true,
									},
								},
							},
							"default_security": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"low_security": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
							"medium_security": schema.SingleNestedBlock{
								MarkdownDescription: "Empty. This can be used for messages where no values are needed",
							},
						},
					},
					"use_host_header_as_sni": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
					"use_mtls": schema.SingleNestedBlock{
						MarkdownDescription: "mTLS Certificate. mTLS Client Certificate",
						Attributes: map[string]schema.Attribute{
						},
						Blocks: map[string]schema.Block{
							"tls_certificates": schema.ListNestedBlock{
								MarkdownDescription: "mTLS Client Certificate. mTLS Client Certificate Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.repeated.max_items: 1 ves.io.schema.rules.repeated.min_items: 1",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"certificate_url": schema.StringAttribute{
											MarkdownDescription: "Certificate. TLS certificate. Certificate or certificate chain in PEM format including the PEM headers. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.certificate_url: true ves.io.schema.rules.string.max_bytes: 131072 ves.io.schema.rules.string.min_bytes: 1",
											Optional: true,
										},
										"description": schema.StringAttribute{
											MarkdownDescription: "Description. Description for the certificate",
											Optional: true,
										},
									},
									Blocks: map[string]schema.Block{
										"custom_hash_algorithms": schema.SingleNestedBlock{
											MarkdownDescription: "Hash Algorithms. Specifies the hash algorithms to be used",
										},
										"disable_ocsp_stapling": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"private_key": schema.SingleNestedBlock{
											MarkdownDescription: "Secret. SecretType is used in an object to indicate a sensitive/confidential field",
										},
										"use_system_defaults": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
									},
								},
							},
						},
					},
					"use_mtls_obj": schema.SingleNestedBlock{
						MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
								Optional: true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
								Optional: true,
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
								Optional: true,
							},
						},
					},
					"use_server_verification": schema.SingleNestedBlock{
						MarkdownDescription: "TLS Validation Context for Origin Servers. Upstream TLS Validation Context",
						Attributes: map[string]schema.Attribute{
							"trusted_ca_url": schema.StringAttribute{
								MarkdownDescription: "Inline Root CA Certificate (legacy). Exclusive with [trusted_ca] Upload a Root CA Certificate specifically for this Origin Pool for verification of server's certificate ves.io.schema.rules.string.max_bytes: 131072 ves.io.schema.rules.string.min_bytes: 1 ves.io.schema.rules.string.truststore_url: true",
								Optional: true,
							},
						},
						Blocks: map[string]schema.Block{
							"trusted_ca": schema.SingleNestedBlock{
								MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name. Required: YES ves.io.schema.rules.message.required: true ves.io.schema.rules.string.max_bytes: 128 ves.io.schema.rules.string.min_bytes: 1",
										Optional: true,
									},
									"namespace": schema.StringAttribute{
										MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace. ves.io.schema.rules.string.max_bytes: 64",
										Optional: true,
									},
									"tenant": schema.StringAttribute{
										MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant. ves.io.schema.rules.string.max_bytes: 64",
										Optional: true,
									},
								},
							},
						},
					},
					"volterra_trusted_ca": schema.SingleNestedBlock{
						MarkdownDescription: "Empty. This can be used for messages where no values are needed",
					},
				},

			},
		},
	}
}

func (r *OriginPoolResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T", req.ProviderData),
		)
		return
	}
	r.client = client
}

func (r *OriginPoolResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data OriginPoolResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.OriginPool{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.OriginPoolSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	created, err := r.client.CreateOriginPool(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create OriginPool: %s", err))
		return
	}

	data.ID = types.StringValue(created.Metadata.Name)
	tflog.Trace(ctx, "created OriginPool resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OriginPoolResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data OriginPoolResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource, err := r.client.GetOriginPool(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read OriginPool: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	if len(apiResource.Metadata.Labels) > 0 {
		labels, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Labels)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Labels = labels
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OriginPoolResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data OriginPoolResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResource := &client.OriginPool{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.OriginPoolSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	updated, err := r.client.UpdateOriginPool(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update OriginPool: %s", err))
		return
	}

	data.ID = types.StringValue(updated.Metadata.Name)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *OriginPoolResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data OriginPoolResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteOriginPool(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete OriginPool: %s", err))
		return
	}
}

func (r *OriginPoolResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
